moodle:
  build: .
  ports:
   - "80:80"
  links:
   - mysql
  restart: always
mysql:
  image: mysql:5.7
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: moodle-password
    MYSQL_DATABASE: moodle
    MYSQL_USER: moodle
